---
title: "2025 NFL Draft CB Grades"
author: "Ayden Matocha"
date: "4/2/2025"
output:
  html_document:
    toc: TRUE
---

# Packages Needed
```{r}
library(tidyverse)
library(DT)
```

# Read CSV File
```{r}
CB_Stats <- read.csv("CB_Rankings.csv")
CB_Stats <- CB_Stats %>%
  arrange(rank) %>%
  mutate(pos_rank_bef = row_number())
datatable(CB_Stats)
```

# Get Mean Values
```{r}
mean(CB_Stats$man_grade)
mean(CB_Stats$zone_grade)
mean(CB_Stats$comp)
mean(CB_Stats$passer_rating)
mean(CB_Stats$missp)
```


# Create Values Function
```{r}
get_cb_values <- function(input_df) {
  df_cb_copy <- input_df %>% mutate(
    man_grade = round(pmax(pmin((man_grade-50) / 4, 10), 0), 2),  # 50-90, mean 70
    zone_grade = round(pmax(pmin((zone_grade-50) / 4, 10), 0), 2), # 50-90, mean 70
    comp = round(pmax(pmin(((100-comp)-25)/4, 10), 0), 2), # 75-35, mean 55
    passer_rating = round(pmax(pmin(((200-passer_rating)-100)/7, 10), 0), 2), # 100-30, mean 70
    missp = round(pmax(pmin(((100-missp)-80)/1.5, 10), 0), 2), # 20-5, mean 12.5
  )
  return(df_cb_copy)
}
```

# Create Final Dataset
```{r}
new_stats_cb <- get_cb_values(CB_Stats) %>% 
  mutate(total = rowSums(select(., -player, -adp, -rank, -pos_rank_bef, -team))) %>% 
  arrange(-total) %>%
  mutate(pos = "CB", pos_rank_aft = row_number(), pos_rank_diff = pos_rank_bef-pos_rank_aft) %>%
  select(player, man_grade, zone_grade, comp, passer_rating, missp, total, rank, pos, team, pos_rank_bef, pos_rank_aft, pos_rank_diff)
datatable(new_stats_cb)
```

# Get Total Value and Rank
get the dataset that only contains the total and the ranks
```{r}
cb_stats_total <- new_stats_cb %>%
  select(player, total, rank, pos, team, pos_rank_bef, pos_rank_aft, pos_rank_diff)
datatable(cb_stats_total)
```

# Download Final Rankings
```{r}
write.csv(cb_stats_total, "cb_stats_total.csv", row.names = FALSE)
```

