---
title: "2025 NFL Draft DL Grades"
author: "Ayden Matocha"
date: "4/2/2025"
output:
  html_document:
    toc: TRUE
---

# Packages Needed
```{r}
library(tidyverse)
library(DT)
```

# Read CSV File
```{r}
DL_Stats <- read.csv("DL_Rankings.csv") %>%
  arrange(rank) %>%
  mutate(pos_rank_bef = row_number())
datatable(DL_Stats)
```


# Get Mean Values
```{r}
mean(DL_Stats$pass_grade)
mean(DL_Stats$run_grade)
mean(DL_Stats$pass_win)
mean(DL_Stats$run_stop)
mean(DL_Stats$prp)
```

# Create Values Function
```{r}
get_dl_values <- function(input_df) {
  df_dl_copy <- input_df %>% mutate(
    pass_grade = round(pmax(pmin((pass_grade-60) / 2, 10), 0), 2),  # 60-80, mean 70
    run_grade = round(pmax(pmin((run_grade-60) / 3, 10), 0), 2), # 60-90, mean 75
    pass_win = round(pmax(pmin((pass_win-4)*1.25, 10), 0), 2), # 4-12, mean 8
    run_stop = round(pmax(pmin((run_stop-4)*1.67, 10), 0), 2), # 4-10, mean 7
    prp = round(pmax(pmin((prp-3)*2.5, 10), 0), 2), # 3-7, mean 5
  )
  return(df_dl_copy)
}
```

# Create Final Dataset
```{r}
new_stats_dl <- get_dl_values(DL_Stats) %>% 
  mutate(total = rowSums(select(., -player, -adp, -rank, -pos_rank_bef, -team))) %>% 
  arrange(-total) %>%
  mutate(pos = "DL", pos_rank_aft = row_number(), pos_rank_diff = pos_rank_bef-pos_rank_aft) %>%
  select(player, pass_grade, run_grade, pass_win, run_stop, prp, total, rank, pos, team, pos_rank_bef, pos_rank_aft, pos_rank_diff)
datatable(new_stats_dl)
```


# Get Total Value and Rank
get the dataset that only contains the total and the ranks
```{r}
dl_stats_total <- new_stats_dl %>%
  select(player, total, rank, pos, team, pos_rank_bef, pos_rank_aft, pos_rank_diff)
datatable(dl_stats_total)
```

# Download Final Rankings
```{r}
write.csv(dl_stats_total, "dl_stats_total.csv", row.names = FALSE)
```