---
title: "2025 NFL Draft TE Grades"
author: "Ayden Matocha"
date: "4/2/2025"
output:
  html_document:
    toc: TRUE
---

# Packages Needed
```{r}
library(tidyverse)
library(DT)
```

# Read CSV File
```{r}
TE_Stats <- read.csv("TE_Rankings.csv")
TE_Stats <- TE_Stats %>% arrange(rank) %>%
  mutate(pos_rank_bef = row_number())
datatable(TE_Stats)
```
# Get Mean Values
```{r}
mean(TE_Stats$rec_grade)
mean(TE_Stats$rb_grade)
mean(TE_Stats$yprr)
mean(TE_Stats$drop)
mean(TE_Stats$ctc)
```


# Create Values Function
```{r}
get_te_values <- function(input_df) {
  df_copy <- input_df %>% mutate(
    rec_grade = round(pmax(pmin((rec_grade-50) / 4, 10), 0), 2),  # 50-90, mean 70
    rb_grade = round(pmax(pmin((rb_grade-40) / 3, 10), 0), 2), # 40-70, mean 55
    yprr = round(pmax(pmin((yprr-1) * 6.67, 10), 0), 2), # 1-2.5, mean 1.75
    drop = round(pmax(pmin(((100-drop)-90) * 1.33, 10), 0), 2), # 10-2.5, mean 6.25
    ctc = round(pmax(pmin((ctc-25) / 4, 10), 0), 2), # 25-65, mean 45
  )
  return(df_copy)
}
```

# Create Final Dataset
```{r}
new_stats_te <- get_te_values(TE_Stats) %>% 
  mutate(total = rowSums(select(., -player, -adp, -rank, -pos_rank_bef, -team))) %>% 
  arrange(-total) %>%
  mutate(pos = "TE", pos_rank_aft = row_number(), pos_rank_diff = pos_rank_bef-pos_rank_aft) %>%
  select(player, rec_grade, rb_grade, yprr, drop, ctc, total, rank, pos, team, pos_rank_bef, pos_rank_aft, pos_rank_diff)
datatable(new_stats_te) 
```

# Get Total Value and Rank
get the dataset that only contains the total and the ranks
```{r}
te_stats_total <- new_stats_te %>%
  select(player, total, rank, pos, team, pos_rank_bef, pos_rank_aft, pos_rank_diff)
datatable(te_stats_total)
```

# Download Final Rankings
```{r}
write.csv(te_stats_total, "te_stats_total.csv", row.names = FALSE)
```

